jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    NODE_VERSION: 10.15.0
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true

  steps:
  #----------------------------------------------------------------------
  # Install all tools and check configuration
  #----------------------------------------------------------------------
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15.0'
    displayName: 'TOOLS: install Node.js'
  - script: sudo /etc/init.d/mysql stop
    displayName: 'TOOLS: stop MySQL'
  #----------------------------------------------------------------------
  # Tests
  #----------------------------------------------------------------------
  - script:  install
    displayName: 'INSTALL: launch  install'
    displayName: 'TESTS: backend'
    displayName: 'TESTS: frontend'
    displayName: 'TESTS: packaging'
